#!/usr/bin/env node
/**
 * analyze-diff.mjs
 *
 * Reads a git diff from stdin, calls the Anthropic Messages API
 * (claude-sonnet-4-6), and writes a markdown GitHub issue body to stdout.
 *
 * Usage:
 *   git diff <before>..<after> | node scripts/analyze-diff.mjs
 *
 * Required env:
 *   ANTHROPIC_API_KEY
 */

// ── 1. Read diff from stdin ───────────────────────────────────────────────────
const diff = await readStdin()

if (!diff.trim()) {
  process.stdout.write('<!-- analyze-diff: empty diff, nothing to review -->\n')
  process.exit(0)
}

// ── 2. Build the prompt ───────────────────────────────────────────────────────
const SYSTEM_PROMPT = `\
You are a code-review assistant for a Next.js 14 (App Router) project that hosts
standalone HTML canvas tools in \`public/tools/\`. Your job is to review a git diff
and identify any Next.js wiring work that a developer needs to do next.

Project conventions:
- Every HTML tool file in \`public/tools/\` needs:
    1. A \`<meta name="tool-id" content="<id>" />\` tag in \`<head>\`
    2. A \`<script src="/tracker.js"></script>\` tag before \`</body>\`
- Every new tool also needs:
    3. A new route at \`app/tools/<name>/page.tsx\` that renders a full-viewport iframe
    4. A new tool-id string added to the VALID_TOOLS Set in \`app/api/event/route.ts\`
    5. A Jest test suite in \`__tests__/canvas/<name>.test.js\` using
       \`loadCircuitScript\` (non-IIFE) or \`loadIifeScript\` (IIFE scripts)
       from \`__tests__/canvas/helpers.js\`
- When canvas logic functions change (snap, gcd, componentSize, getComponentNodes,
  rotatePoint, getLocalNodes), the corresponding __tests__/canvas/ suite likely
  needs updating.
- GRID=28, COMPONENT_SCALE=0.8 for circuit_diagram_creatorv2.html
- GRID=22.4 for circuit_diagram_secjc.html; includes transistor (3-node) and transformer (2-node)
- object_circuitv2.html: COMPONENT_SCALE=0.8 for battery/switch, BULB_SCALE=1 (bulb nodes unscaled)
`

// Truncate at 48 000 chars to avoid runaway costs on huge diffs
const diffSnippet = diff.length > 48_000
  ? diff.slice(0, 48_000) + '\n\n[... diff truncated at 48 000 chars ...]'
  : diff

const USER_PROMPT = `\
Below is a git diff from a push by JulesWyrm. Analyse it and produce a GitHub
issue body in Markdown describing the Next.js wiring work needed.

Structure your response as:
1. A short (2-3 sentence) **Summary** of what changed.
2. A **Checklist** of actionable tasks (GitHub task-list syntax: \`- [ ] ...\`),
   covering where relevant:
   - New \`public/tools/\` HTML files that need a Next.js page
   - Missing or incorrect \`<meta name="tool-id">\` tags
   - Missing \`<script src="/tracker.js">\` tags
   - New tool-ids to add to VALID_TOOLS in \`app/api/event/route.ts\`
   - New Jest test suites to create in \`__tests__/canvas/\`
   - Existing canvas test suites that need updating due to logic changes
3. A **Files changed** section listing every file touched in the diff.

If nothing in the diff requires Next.js wiring work, say so clearly and keep the
issue body short.

\`\`\`diff
${diffSnippet}
\`\`\`
`

// ── 3. Call the Anthropic Messages API ───────────────────────────────────────
const apiKey = process.env.ANTHROPIC_API_KEY
if (!apiKey) {
  process.stderr.write('ERROR: ANTHROPIC_API_KEY is not set\n')
  process.exit(1)
}

const response = await fetch('https://api.anthropic.com/v1/messages', {
  method: 'POST',
  headers: {
    'x-api-key': apiKey,
    'anthropic-version': '2023-06-01',
    'content-type': 'application/json'
  },
  body: JSON.stringify({
    model: 'claude-sonnet-4-6',
    max_tokens: 2048,
    system: SYSTEM_PROMPT,
    messages: [{ role: 'user', content: USER_PROMPT }]
  })
})

if (!response.ok) {
  const errText = await response.text()
  process.stderr.write(`ERROR: Anthropic API returned ${response.status}: ${errText}\n`)
  process.exit(1)
}

const data = await response.json()
const issueBody = data?.content?.[0]?.text ?? ''

if (!issueBody) {
  process.stderr.write('ERROR: Unexpected response shape from Anthropic API\n')
  process.stderr.write(JSON.stringify(data, null, 2) + '\n')
  process.exit(1)
}

// ── 4. Write issue body to stdout ─────────────────────────────────────────────
const footer = [
  '',
  '---',
  '*Auto-generated by [analyze-diff.mjs](../scripts/analyze-diff.mjs) · model: claude-sonnet-4-6*'
].join('\n')

process.stdout.write(issueBody + footer + '\n')

// ── Helpers ───────────────────────────────────────────────────────────────────
async function readStdin () {
  const chunks = []
  for await (const chunk of process.stdin) {
    chunks.push(chunk)
  }
  return Buffer.concat(chunks).toString('utf8')
}
